### ISSUE TITLE
database basic error

### ISSUE THREAD

**Issue by sathanu** [huntlabs/database#11]
I have downloaded this. and run the example mysql. but it throws below error

Dlang\database-0.1.0\examples\mysql>dub run
Performing "debug" build using dmd for x86.
database ~master: building configuration "mysql"...
mysql_demo ~master: building configuration "default"...
Linking...
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
mysqlclient.lib
 Warning 2: File Not Found mysqlclient.lib
libmysql.lib
 Warning 2: File Not Found libmysql.lib
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_close@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_set_character_set@8
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_real_connect@32
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_init@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_query@8
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_get_client_info@0
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_error@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_ping@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_thread_id@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_insert_id@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_affected_rows@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_store_result@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(connection)
 Error 42: Symbol Undefined _mysql_real_escape_string@16
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_free_result@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_num_rows@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_num_fields@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_lengths@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_row@4
..\..\.dub\build\mysql-debug-windows-x86-dmd_2077-E7A5679D03D9D572856F6EF183C4ADBE\database.lib(resultset)
 Error 42: Symbol Undefined _mysql_fetch_fields@4
Error: linker exited with status 19
dmd failed with exit code 19.

Dlang\database-0.1.0\examples\mysql>

**Comment by zoujiaqing** [comment]
upgrade hunt-database version to latest :)

**Comment by zoujiaqing** [comment]
Only support 64-bit for Windows
