### ISSUE TITLE
Does not appear to handle boolean for PostgreSQL correctly

### ISSUE THREAD

**Issue by ximion** [huntlabs/database#19]
When trying to insert a boolean value into a table (created via hunt-entity), this error appears:
```
2018-09-08T21:16:34.378:statement.d:execute:84  INSERT INTO public.users(name,email,money,status) VALUES('Brian','test@example.com',99.9,0) returning id 
hunt.database.exception.DatabaseException@../source/hunt/database/driver/postgresql/connection.d(83): DB SQL :  INSERT INTO public.users(name,email,money,status) VALUES('Brian','brian@huntlabs.cn',99.9,0) returning id 
DB status : 7 
EXECUTE ERROR : 7
ERROR:  Column »status« has type boolean, but expression has type integer
LINE 1: ...y,status) VALUES('Brian','brian@huntlabs.cn',99.9,0) returni...
                                                             ^
```
This can either be solved by doing a type conversion in the expression (converting `0` into a bool), or by giving the database a boolean `t`/`f` value in the first place.

Btw, I think hunt-entity and hunt-database could really benefit from some integration tests with different databases - unfortunately those are a bit annoying to do in D. Maybe I can come up with something in my spare time.

**Comment by zhangyuchun** [comment]
yes. we need more integration tests.  this's is a entity's bug. fix at https://github.com/huntlabs/hunt-entity/commit/e02f4c89d8d86019e23ac3136d19cab6af2e3c47.
