### ISSUE TITLE
Schema support for row

### ISSUE THREAD

**Issue by aberba** [huntlabs/database#2]
It can be very covenient to have schema for binding to row fetched from DB like:

```d
// structured row annotations
	struct PlaceFull {
		uint id;
		string name;
		@optional string thumbnail;	// ok to be null or missing
		@optional GeoRef location;	// nested fields ok to be null or missing
		@optional @as("contact_person") string contact; // optional, and sourced from field contact_person instead

		@ignore File tumbnail;	// completely ignored
	}
```

And used as:

```d
// after fetchning
auto place = row.toStruct!PlaceFull;
```

furthure
```d
// automated struct member uncamelcase
	@uncamel struct PlaceOwner {
		uint placeID;			// matches placeID and place_id
		uint locationId;		// matches locationId and location_id
		string ownerFirstName;	// matches ownerFirstName and owner_first_name
		string ownerLastName;	// matches ownerLastName and owner_last_name
		string feedURL;			// matches feedURL and feed_url
	}
```

This resulting schema (strict) can easily be used to generate a json output for rest api. Private columns can be marked with @ignore

**Comment by aberba** [comment]
Or is it appropriate when implemented as a library

**Comment by viile** [comment]
yes, We have implemented this library,  [entity](https://github.com/huntlabs/entity)  Object-relational mapping based JPA

**Comment by aberba** [comment]
Its seems nice (even though it has Java look and feel to its naming of things). How much can it do outside basic CRUD?

The one show in my issue above is more of a schema. It does not restrict you to certain operations/interface and .... that struct (schema) can be reused in several operations whether those tables have the column for all of them or not. Its a small abstraction for extracting the data automatically without any CRUD.

**Comment by Heromyth** [comment]
Thanks for your suggestion. We will add more features like these in future [entity](https://github.com/huntlabs/entity).  We want this library to be kept simple and stable firstly. Of course, more UDAs and metholds will be added to make the database model more readable and usable.

**Comment by dejlek** [comment]
This will work in some teams (those that use snake-case naming in their databases). What with teams that prefer all upper-case names, camel-case, or any other naming convention. This is the main reason people ignore DB tools that make wrong assumptions from the start...

**Comment by aberba** [comment]
take a look at https://github.com/eBookingServices/mysql-lited ans see how they handle it nicely with `toStruct`

**Comment by zoujiaqing** [comment]
@aberba @dejlek We released new version Entity. Have stable APIs and enhacemants.
https://github.com/huntlabs/entity
