### ISSUE TITLE
assertion fails on setParameter for prepared INSERT statement

### ISSUE THREAD

**Issue by p-mitana** [huntlabs/database#21]
I am trying to insert some data into a table.

    Statement statement = db.prepare(`INSERT INTO users (email, first_name, last_name) VALUES (:email, :firstName, :lastName`);
    statement.setParameter(`:email`, "me@example.com");
    statement.setParameter(`:firstName`, "John");
    statement.setParameter(`:lastName`, "Doe");
    statement.execute();

However, an assertion fails.

    core.exception.AssertError@/home/mitu/.dub/packages/hunt-database-0.2.2/hunt-database/source/hunt/database/statement.d(62): Assertion failure

I noticed that for SELECT queries (with params in WHERE clause) it works properly, but for INSERTs it does not.

**Comment by zhangyuchun** [comment]
the code parse sql has some bug , will be fix in the future. 
at this time you can write code like this , (more  blank space between keys):

Statement statement = db.prepare("INSERT INTO users ( email , first_name , last_name ) VALUES ( :email , :firstName , :lastName )");

**Comment by zoujiaqing** [comment]
@the-Mitu Fixed of v1.0.0
