### ISSUE TITLE
Cannot build with SQLite

### ISSUE THREAD

**Issue by p-mitana** [huntlabs/database#28]
Errors:

    ../../../.dub/packages/hunt-database-1.1.1/hunt-database/source/hunt/database/driver/sqlite/Connection.d(71,25): Error: undefined identifier `buildPath`
    ../../../.dub/packages/hunt-database-1.1.1/hunt-database/source/hunt/database/driver/sqlite/Connection.d(76,9): Error: undefined identifier `trace`

**Comment by zoujiaqing** [comment]
I fixed it.
