### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ernibert** [huntlabs/database#35]
Since D may be new for people (at least to me it is) and that D will be available in gcc-9, i think it would be great to get a hint on how to setup the D ecosystem properly.
The hunt-database stuff looks pretty professional and i would love to include it into a small (and first) D-project.

I tried following:

$ tar -xf hunt-database-1.2.0-rc.1.tar.gz
$ cd cd hunt-database-1.2.0-rc.1
$ mkdir build
$ cd build
$ meson --prefix=/tmp/test ..
The Meson build system
Version: 0.49.2
Source dir: /home/lfs/belfspm/trunk/belfs_d/hunt-database-1.2.0-rc.1
Build dir: /home/lfs/belfspm/trunk/belfs_d/hunt-database-1.2.0-rc.1/build
Build type: native build
Project name: hunt-database
Project version: 1.1.1
Native D compiler: gdc (gcc 9.0.1 "gdc (GCC) 9.0.1 20190331 (experimental)")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:61:0: ERROR:  Failed to initialize 'subprojects/hunt-sql':
Subproject directory not found and hunt-sql.wrap file not found

A full log can be found at /home/lfs/belfspm/trunk/belfs_d/hunt-database-1.2.0-rc.1/build/meson-logs/meson-log.txt

---
What am i doing wrong?

**Comment by Heromyth** [comment]
It's so sad. We always make sure that the DUB works at first. We hope this problem will be fixed before next release.

**Comment by Heromyth** [comment]
So sorry! Meon supports is deprecated after Hunt-Database v2.0.
