### ISSUE TITLE
Why is RowSet no more a range?

### ISSUE THREAD

**Issue by p-mitana** [huntlabs/database#38]
I've just tried 2.0 beta version. However I find it very problematic that RowSet is no more an InputRange. Until now I could freely use all the D's algorithms directly on RowSet (and I used it everywhere). With 2.0 most of my code broke.

Also, sometimes I just need the first row and don't want to use foreach anyway.

Could the RowSet be made an InputRange again?

**Comment by Heromyth** [comment]
There is a method named iterator() in RowSet, which is an InputRange.

**Comment by p-mitana** [comment]
OK, I haven't noticed that. Thank you!
