### ISSUE TITLE
Does not build for SQLite on Linux

### ISSUE THREAD

**Issue by p-mitana** [huntlabs/database#4]
Hello, I'm trying to build with SQLite support for Linux. An error appears:

    ../../../../../../home/mitu/.dub/packages/database-0.0.9/database/source/database/driver/sqlite/connection.d(120,52): Error: cannot implicitly convert 
    expression `sqlite3_last_insert_rowid(this.conn)` of type `long` to `int`
    ../../../../../../home/mitu/.dub/packages/database-0.0.9/database/source/database/url.d(306,20): 
    Deprecation: variable database.url.URL.query is deprecated - use queryParams
    ../../../../../../home/mitu/.dub/packages/database-0.0.9/database/source/database/url.d(309,28): 
    Deprecation: variable database.url.URL.query is deprecated - use queryParams
    ../../../../../../home/mitu/.dub/packages/database-0.0.9/database/source/database/url.d(493,13): 
    Deprecation: variable database.url.URL.query is deprecated - use queryParams

The compiler is DMD 2.076.

**Comment by viile** [comment]
thank, I've already fixed it

**Comment by p-mitana** [comment]
Would you mind tagging the release, so that I could use the fixed library?
Thaks for your work :)

**Comment by viile** [comment]
Of course, tag "0.0.10" already released

**Comment by p-mitana** [comment]
Cool, thanks again! :)
