### ISSUE TITLE
[PostgreSQL] VariantException in count() method

### ISSUE THREAD

**Issue by p-mitana** [huntlabs/database#40]
Stack trace:

    std.variant.VariantException@std/variant.d(1715): Variant: attempting to use incompatible types long and int
    /usr/include/dmd/phobos/std/variant.d:836 inout @property inout(int) std.variant.VariantN!(32uL).VariantN.get!(int).get() [0x55c4f05eea50]
    ../../.dub/packages/hunt-database-2.0.0-beta.4/hunt-database/source/hunt/database/base/impl/ArrayTuple.d:100 int hunt.database.base.impl.ArrayTuple.ArrayTuple.getInteger(int) [0x55c4f0625601]
    ../../.dub/packages/hunt-database-2.0.0-beta.4/hunt-database/source/hunt/database/Statement.d:200 int hunt.database.Statement.Statement.count() [0x55c4f05adeaa]
    [...]

hunt-database 2.0.0-beta.4, PostgreSQL 11.

**Comment by Heromyth** [comment]
It seems has been fixed in recent commits.
