### ISSUE TITLE
sqlite connection

### ISSUE THREAD

**Issue by MistrzPiwny** [huntlabs/database#5]
Hi when i try to connect with sqlite database i got this error
`database.exception.DatabaseException@../../../.dub/packages/database-0.0.13/database/source/database/pool.d(62): Don't support database driver: sqlite
----------------
??:? database.driver.connection.Connection database.pool.Pool.initConnection() [0x86a7c1cd]
??:? database.pool.Pool database.pool.Pool.__ctor(database.option.DatabaseOption) [0x86a7c0bf]
??:? void database.database.Database.initPool() [0x86a76483]
??:? database.database.Database database.database.Database.__ctor(immutable(char)[]) [0x86a76423]
??:? _Dmain [0x86a7551b]
Program exited with code 1`

OS: Deepin 15.4.1 64bit
DMD64 D Compiler v2.076.1

**Comment by dangbinghoo** [comment]
you should do the compilation using configuration sqlite. 
			`"subConfigurations": {
				"database": "sqlite"	
			},`

**Comment by viile** [comment]
Refer to the config file

https://github.com/huntlabs/database/blob/master/examples/sqlite/dub.json
