### ISSUE TITLE
Example provided for the prepare method doesn't seem to be working

### ISSUE THREAD

**Issue by vinoakash** [huntlabs/database#51]
Hi All,

  The below code is not working and throwing the below error after analyzing we found the the prepare method expects a SqlConnection as first argument and a string as second argument where in the example provide in the link does not state the same, so would request you to update the document with correct procedure.

**Eg from the example document https://code.dlang.org/packages/hunt-database**
`"Statement stmt = db.prepare("SELECT * FROM user where username = :username and age = :age LIMIT 10");"`
 
**Code**
******File : GetConnections.d******

`module common.GetConnections;
import hunt.database;

class dbconnect
{
  public Database con;
  this() { con = new Database("mysql://username:password@localhost:3910/testdb"); }
}`

******File: GetConfig.d******

`import common.GetConnections;
import hunt.database;

auto getConfig(int Seq)
{
 auto mdb = new dbconnect();
 Statement stmt = mdb.con.prepare("SELECT * FROM settings WHERE Seq = :Sq");
           stmt.setParameter("Sq", Seq);
           stmt.execute();
 RowSet rs = stmt.query();
 mdb.conn.close();
 return rs;
}`

****Note: Seq is of type int****
******File : app.d******
`import std.stdio;
imoprt common.GetConfig;

void main() {
writeln(getConfig(1));
}`
##################################################################################
**Error:**
GetConfig.d
Error: function hunt.database.Database.Database.prepare(SqlConnection conn, string sql) is not callable using argument types (string)
 cannot pass argument "SELECT * FROM settings WHERE Seq = :Sq" of type string to parameter SqlConnection conn
Error: template hunt.database.Statement.Statement.setParameter cannot deduce function from argument types !()(int, int), candidates are:

**Comment by vinoakash** [comment]
We are evaluating various packages such as web frame work(vibe and hunt framework) , Json(std.json, std_data_json, vibe.data.json and asdf) and Mysql driver (mysql-native, and hunt-database) for our migration project.  Expect hunt libraries we have completed evaluating other packages. We almost spent 3 day, still we are not able to progress our testing using hunt packages as the basic functionality of connecting to database itself is not working as intended and the readme document is not up to date as the  last update is 14 month’s back. We understand that the people created this package are not dedicated resource at the same time we wonder whether the intention of the package creator is to use this package by other’s nor is this package been developed for his personnel use, we are not sure how good is this package as the basic functionality are not working.  If the package creator cannot provide any support nor if this package is for his own use, then it would be good to update this info explicitly so that other users can decide whether to use such package.

**Comment by Heromyth** [comment]
All the hunt-* projects are open to anyone who wants to use it. For this, we will test and fix it as soon as possible.

PS: Any feedbacks are welcome to be submitted here.

**Comment by Heromyth** [comment]
It's fixed in commit https://github.com/huntlabs/hunt-database/commit/67e2ba703e918a503d1db30546c7124b51a714bf.
Here is a working [example](https://github.com/huntlabs/hunt-database/blob/master/examples/mysql/source/app.d).

**Comment by Heromyth** [comment]
Our projects are using [Hunt-Entity](https://github.com/huntlabs/hunt-entity/) heavily 
which is based on Hunt-Database. 

You can have a try for it.

**Comment by vinoakash** [comment]
Hi,

  Thank you very much, based on our test result ( https://forum.dlang.org/thread/uhgnkjczoarasacxkcod@forum.dlang.org ) we have planned to use hunt libraries heavily in our migration project, So we would need some help such like this. We have tested the new version 2.1.11 as it is working as expected, there is one warning for which we have raised an issue #52 , we have noticed several issue for which we will raise those as a separate issue.
