### ISSUE TITLE
Warning : [warning] __lambda1 - _tcpConnection is null - 

### ISSUE THREAD

**Issue by vinoakash** [huntlabs/database#52]
Hi All,

  Every time when we execute the code we are getting the below warning, not sure what is this warning menas and how to resolve this issue.

2020-11-09 07:11:16 (3585) [warning] __lambda1 - _tcpConnection is null - /root/.dub/packages/hunt-net-0.5.4/hunt-net/source/hunt/net/NetClientImpl.d:162

Code:
module common.GetApiconf;

import common.GetConnections;
import core.stdc.stdlib: exit;
import hunt.database;

auto getApiconf(string stack)
{
 Row[] apiconfig;
 auto con = new Connections();
 Statement stmt = con.db.prepare("SELECT apiuri FROM apisettings WHERE stack = :stack");
 stmt.setParameter("stack", stack);
 RowSet apistore = stmt.query();
 scope(failure) { con.db.close(); exit(-2); } scope(exit) con.db.close();
 foreach(i; apistore) { apiconfig ~= i; }
 return apiconfig;
}

From,
Vino.B

**Comment by Heromyth** [comment]
It's just a normal debug message. Maybe, it will be removed in the next release of Hunt-Net.

**Comment by Heromyth** [comment]
Fixed in commit https://github.com/huntlabs/hunt-net/commit/94adf24c3c495674d88790d24ad9956107dde056.
