### ISSUE TITLE
Prepared Insert Fails

### ISSUE THREAD

**Issue by vinoakash** [huntlabs/database#53]
HI All,

  The below prepred insert fails with the below MySQL error, hence request your help.

 auto con = new Connections();
 Statement stmt = con.db.prepare("INSERT INTO test (Type) VALUES(:Typ)");
 stmt.setParameter(":Typ", "DEV");
 stmt.execute();

MySQL Error:
2020-Nov-09 17:21:09.0039376 | 16107 | warning | SqlClientBase.query | You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':Typ)' at line 1 | /root/.dub/packages/hunt-database-2.1.11/hunt-database/source/hunt/database/base/impl/SqlClientBase.d:94
hunt.database.base.Exceptions.DatabaseException@/root/.dub/packages/hunt-database-2.1.11/hunt-database/source/hunt/database/base/impl/SqlClientBase.d(96): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':Typ)' at line 1

**Comment by vinoakash** [comment]
Hi All,

  Was able to resolve this issue 

auto con = new Connections();
Statement stmt = con.db.prepare("INSERT INTO test (Type) VALUES(:Typ)");
stmt.setParameter(":Typ", "DEV");  \\ issue is ";Typ" it should be "Typ"
stmt.execute();

**Comment by Heromyth** [comment]
Sorry, what happened here:)
