### ISSUE TITLE
Deprecation: module hunt.util.Serialize is deprecated - It's buggy. Use hunt.serialization.JsonSerializer instead

### ISSUE THREAD

**Issue by vinoakash** [huntlabs/database#55]
Hi All,

   Would it be possible to clear all such deprecation in next release as we tried to adopt to the change as specified, few programs worked and few other's started to throw different error.

/root/.dub/packages/hunt-sql-1.4.5/hunt-sql/source/hunt/sql/stat/TableStat.d(21,8): Deprecation: module hunt.util.Serialize is deprecated - It's buggy. Use hunt.serialization.JsonSerializer instead.

**Comment by Heromyth** [comment]
We are trying.

**Comment by Heromyth** [comment]
Fixed in commit https://github.com/huntlabs/hunt-sql/commit/a8f0fc267c945c54ee81e5d2a665f7dd73399fa2.
