### ISSUE TITLE
PosttgreSQL Connection not working

### ISSUE THREAD

**Issue by vinoakash** [huntlabs/database#59]
Hi All,

Below below code is not working and it throws "**Can't get a working DB connection.**", I am trying to insert a record into a table name "Backup", which has a single column named "Name" for type "Name" , the same query works from command line, and the username/password are correct. PostgreSQL is installed on Windows localhost.

`import std.stdio;
import hunt.database;

void main()
{
    writeln("run database PostgreSQL demo.");
    auto db = new Database("postgresql://admin:Welcome1234@localhost:5432/Dbtest");
    int result = db.execute(`INSERT INTO public."Backup"("Name") Values('Test');`);
    writeln(result);
    foreach(row; db.query(`SELECT * FROM public."Backup"`))
    {
        writeln(row["Name"]);
    }
    db.close();
}`

**Comment by vinoakash** [comment]
The issue is similar to the issue "PostgreSQL (14.0) driver: It seems that scram-sha-256 authentication is not supported ", now resolved by updating the below files

**File: pg_hba.conf:** 

`#`"local" is for Unix domain socket connections only
local   all             all                                              md5
 IPv4 local connections:
host    all             all             0.0.0.0                      md5
host    all             all             127.0.0.1/32             md5`

**File: postgresql.conf**
`listen_addresses = '127.0.0.1'`

**Comment by vinoakash** [comment]
Issue Resolved, Not sure whether it it the right solution

**Comment by Heromyth** [comment]
> The issue is similar to the issue "PostgreSQL (14.0) driver: It seems that scram-sha-256 authentication is not supported ", now resolved by updating the below files
> 
> **File: pg_hba.conf:**
> 
> `#`"local" is for Unix domain socket connections only local all all md5 IPv4 local connections: host all all 0.0.0.0 md5 host all all 127.0.0.1/32 md5`
> 
> **File: postgresql.conf** `listen_addresses = '127.0.0.1'`

We'll have a test for this.
