### ISSUE TITLE
setParameter is not implemented but documented in README

### ISSUE THREAD

**Issue by tirkarthi** [huntlabs/database#6]
I tried out the below and looked the source code it seems that setParameter is not implemented but it's present in the README.md . Is there a way to bind values to prepared statements ?

```D
    string sql = "INSERT INTO testing(data) VALUES (':value');";
    auto stmt = db.prepare(sql);
    stmt.setParameter("value", value);
```

Empty implementation : https://github.com/huntlabs/database/blob/74ddf46ee42722d2e7967986b0d5fff1f468601c/source/database/statement.d#L42

Thanks

**Comment by viile** [comment]
In the latest version 0.0.16, we have implemented this function

**Comment by tirkarthi** [comment]
@viile Thanks for the fix. I tested the new version with dub and PostgreSQL. It seems that it's dropping the bind values. I removed the assert in the `setParameter` function since the `param_value` variable was empty.

```D
import std.conv;
import std.stdio;
import database;

void main()
{
  auto db = new Database("postgresql://root:root@localhost:5432/shouter");

  foreach(number; 1..3) {
    auto value = "Test " ~ to!string(number);
    Statement stmt = db.prepare("SELECT * FROM testing where data = :value");
    stmt.setParameter(":value", value);
    writeln(stmt.sql);
  }

  foreach(row; db.query("SELECT * FROM testing"))
    {
      writeln(row["data"]);
    }
}
```

Sample output : 

```shell
➜  db-tut dub run
Performing "debug" build using dmd for x86_64.
database 0.0.16: target for configuration "postgresql" is up to date.
db-tut ~master: building configuration "default"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./db-tut
SELECT * FROM testing where data =
SELECT * FROM testing where data =
2017-12-22T10:20:05.387:connection.d:query:35 SELECT * FROM
```

**Comment by viile** [comment]
already fixed

**Comment by tirkarthi** [comment]
I think there are also some other issues as below. The parameter is not quoted with single quote while being sent to PostgreSQL and hence it generates below SQL 

`SELECT * FROM testing where data = Test 1`

```D
  void setParameter(T = string)(string key, T value)
  {
    param_value[key] = "'" ~ value.to!string ~ "'";
  }
```

The above change generates the correct SQL but it might be prone to SQL injection.

`SELECT * FROM testing where data = 'Test 1'`

**Comment by tirkarthi** [comment]
@viile Added a unit test and formatted the code. It's a workaround and I will try for a proper solution over the weekend looking into how other libraries do this.

Unit test : https://github.com/tirkarthi/database/commit/f9d1a44940748b98be7eddc413786a67a5859e8e#diff-acd2545e2b9c057905921381db98b299R225

**Comment by viile** [comment]
mysql,pgsql,sqlite have different open and close quote, I have implemented this  in  dialect (https://github.com/huntlabs/database/blob/master/source/database/driver/dialect.d)
